stages:
  - check
  - test

check-code:
  stage: check
  script:
    - "apply_overlay bc-java ./"
    - ". cienv.sh; \ gradle check -x test;"

test-code:
  stage: test
  script:
    - "apply_overlay bc-java ./"
    - ". cienv.sh; \ gradle -stacktrace clean build;"
